modLoader="javafml"
loaderVersion="[36,)"
license="The MIT License (MIT)"
issueTrackerURL="https://github.com/Tomson124/SimplyJetpacks2/issues"

[[mods]]
modId="simplyjetpacks"
version="${file.jarVersion}"
displayName="Simply Jetpacks 2"
updateJSONURL="https://raw.githubusercontent.com/simplyjetpacks/updates/main/simplyjetpacks2/update.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/simply-jetpacks-2"
logoFile="logo.png"
credits="cybercat5555"
authors="StormedPanda, Tomson124"
description='''
Simply Jetpacks 2
Jetpacks and Fluxpacks powered by Forge Energy!
Original Author: tonius11
'''

[[dependencies.simplyjetpacks]]
modId="forge"
mandatory=true
versionRange="[36,)"
ordering="NONE"
side="BOTH"

[[dependencies.simplyjetpacks]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5,1.17)"
ordering="NONE"
side="BOTH"

[[dependencies.simplyjetpacks]]
modId="curios"
mandatory=false
versionRange="[1.16.5-4.0.5.2,)"
ordering="AFTER"
side="BOTH"

[[dependencies.simplyjetpacks]]
modId="cofh_core"
mandatory=false
versionRange="[1.4,)"
ordering="NONE"
side="BOTH"

[[dependencies.simplyjetpacks]]
modId="thermal"
mandatory=false
versionRange="[1.4,)"
ordering="NONE"
side="BOTH"

[[dependencies.simplyjetpacks]]
modId="redstone_arsenal"
mandatory=false
versionRange="[0.8.0b.2,)"
ordering="NONE"
side="BOTH"

[[dependencies.simplyjetpacks]]
modId="redstonerepository"
mandatory=false
versionRange="[1.16.5-2.6.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.simplyjetpacks]]
modId="mekanism"
mandatory=false
versionRange="[1.16.5-507,)"
ordering="NONE"
side="BOTH"

[[dependencies.simplyjetpacks]]
modId="immersiveengineering"
mandatory=false
versionRange="[10,)"
ordering="NONE"
side="BOTH"
